### ISSUE TITLE
Hide config from version control

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#10]
So that credentials aren't commited to GH.

**Comment by iherman** [comment]
I am not sure what the question is...

The OAUTH Token of GH actually _cannot_ be committed to GH. If you do, GH realizes that and will immediately invalidate the key (it happened to me once). That is one of the reasons why I had to have a config file (`~/.scribejs.json` or `CGI-Executable/.scribe.json`) that is never on the Web and can carry the Key.

**Comment by iherman** [comment]
Oh I am sorry, I get it. But the config file in the test directory does NOT include the GH Token. And it cannot, see https://github.com/w3c/scribejs/issues/10#issuecomment-309047533. On the other hand, it is useful if others want to test it.

**Comment by tripu** [comment]
@iherman:

> *&ldquo;But the config file in the test directory does NOT include the GH Token.&rdquo;*

It might, at some point.
Or other sensitive info, like local paths or hostnames, username/password for our CVS server, a developer key for the W3C API&hellip;

It's good practice to exclude configuration and all particulars from version control, imho. They vary from user to user. And apart from the security concerns, changes in config files add noise to the Git history.

> *&ldquo;And it cannot, see https://github.com/w3c/scribejs/issues/10#issuecomment-309047533.&rdquo;*

It's kind of funny GitHub is catching its own tokens inside attempted commits and aborting them&hellip; I guess it's a nice feature, but we should not rely on that.

**Comment by iherman** [comment]
Ok. I have removed the example config files.
