### ISSUE TITLE
Refactor "convert.io" using regex'es instead?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#12]

**Comment by iherman** [comment]
You mean `convert.js`:-)

I would actually prefer to close this issue with no action. The current approach is, though more verbose and probably slower, is much more clean and maintainable, and the price in speed is not relevant for minutes that are really not that large computing-wise...

**Comment by tripu** [comment]
> *&ldquo;You mean `convert.js` :-)&rdquo;*

Yes! :innocent:

I think those `startsWith()` and custom functions for filtering are too verbose; I would find regexes actually easier to parse.

But I defer to you on this.
