### ISSUE TITLE
CGI: add option to commit to w3.org space instead of GH repo?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#14]

**Comment by iherman** [comment]
Is there any decent package to use with CVS? I looked at [search](https://www.npmjs.com/search?q=cvs) but this did not seem to show anything... Taking into account that CVS is frown upon these days, I would not be surprised if there wasn't any:-(

**Comment by tripu** [comment]
There doesn't seem to be any one&hellip;

**Comment by iherman** [comment]
In that case, I propose closing this. Or it can be considered as postponed until either there is a CVS interface, or there are other means to access the W3C space...

**Comment by tripu** [comment]
Okay then to ignore this for the time being, @iherman.

I prefer to keep it open, though, as I suspect some groups and individuals will push to keep CVS in their work cycle&hellip;

(If there are no packages in npm to help us write a simple CVS client, we can always spawn shell processes invoking `cvs` manually, eg via [`child_process.spawn()`](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options).)

**Comment by iherman** [comment]
The CGI version is gone, making this issue obsolete.
