### ISSUE TITLE
Review input sanitisation

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#15]
eg, in HTTP params

**Comment by tripu** [comment]
eg, sanitise URI entered in the HTML form (`../` allowed?)

**Comment by tripu** [comment]
cf [`https://blog.risingstack.com/node-js-security-checklist/`](https://blog.risingstack.com/node-js-security-checklist/)

**Comment by iherman** [comment]
See https://github.com/w3c/scribejs/issues/16#issuecomment-327529806

**Comment by iherman** [comment]
Issue moot with the disappearance of the CGI version
