### ISSUE TITLE
Use npm package 'octocat' instead of interacting directly with the GH API?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#17]

**Comment by iherman** [comment]
I remember having looked at it briefly, but I found out that using the GH API directly using simply `fetch` was actually simpler for what I needed. To be honest, I do not really remember how I got to that conclusion but, if things can be used by direct `fetch` then this seems to be better...

**Comment by tripu** [comment]
(I wasted some time trying to use `octocat`, but that package is poor and incomplete :unamused: The one we've used in other projects is `octokat`.)
