### ISSUE TITLE
Do we need field “files” in “package.json”?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#25]
[Documentation says](https://docs.npmjs.com/files/package.json#files) that that's a list of files to be included, but [`npm publish` includes all files in the current dir](https://docs.npmjs.com/cli/publish), anyway (unless explicitly excluded).

So, what's the point of that list? It has to be manually maintained, eg updated every time a file is added/removed/renamed&hellip;

See #24.

**Comment by iherman** [comment]
@tripu I must admit I do not know. I just followed what npm seems to do and what is in the documentation...

**Comment by tripu** [comment]
Okay, I think we can remove that section. I'll do that.
