### ISSUE TITLE
Whitespace and coding style?

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/scribejs#46]
Currently the files are a mix of tabs and spaces--which means things don't always line up across different peoples tab preferences.

Would you be open to a PR that changes the whitespace to the (pretty typical for JS) 2 space characters per indentation level? See https://github.com/airbnb/javascript#whitespace for an example.

Additionally, I'd be happy to setup an [.eslintrc](https://eslint.org/) and [.editorconfig](https://editorconfig.org/) file to help keep things consistent going forward.

Your call, though. 😄

**Comment by tripu** [comment]
fwiw, the current &ldquo;standard&rdquo; for [JS projects at the W3C](https://github.com/w3c?utf8=%E2%9C%93&q=&type=&language=javascript) is:

* 2 spaces for indentation
* [ESLint](https://eslint.org/) (although most projects are still using the old [JSCS](https://github.com/jscs-dev/node-jscs))
* [JSHint](http://jshint.com/docs/)

(See [*&sect; Technical Decisions* in the Design / Style Guide repo](https://w3c.github.io/design/templates/technical-decisions)&nbsp;&mdash;&nbsp;although it's WIP, incomplete, not reviewed widely yet.)

I personally try to have an [`.editorconfig` file](https://editorconfig.org/) in my projects too, when I have the time for that.

**Comment by iherman** [comment]
@tripu, well, I hate it. I always have difficulties to see the correct structure when using two spaces.

**Comment by tripu** [comment]
In that case, four spaces in this particular project is good enough a compromise for me, @iherman.

**Comment by tripu** [comment]
Closed by @BigBlueHat in #50.
