### ISSUE TITLE
Add JSON-LD to Jekyll preamble

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/scribejs#53]
I added JSON-LD island/data-block output support to the JSON-LD WG's home page:
https://github.com/w3c/json-ld-wg/commit/8194de6a682b32c3679361d80942fe16612d36a9#diff-2c19d9859b055d0302043d0fa2833e3f

I'd love it if we could generate some JSON-LD and add that to the Jekyll preamble for the minutes we generate ever week!

The idea is to provide more meaningful data, so @azaroth42 (and others) can write robots to figure out who hasn't scribbed recently, etc. 😁 

I plan to submit a PR, but thought opening an issue for this would be best organizationally. 😃

**Comment by iherman** [comment]
I am fine you trying:-)

**Comment by iherman** [comment]
@BigBlueHat 
I looked at this, but it is not obvious what schema.org snippet to add. Here is what I've come up with, which strikes the balance between what may be meaningful in schema.org land and may be easily generated based on the information that is available for the script without the need to add additional configuration entries:

```json
{
    "@context": "http://schema.org/",
    "@type": "CreativeWork",
    "name": "JSON-LD Working Group Telco — Minutes",
    "about": "JSON-LD Working Group Telco",
    "dateCreated": "2019-03-29",
    "genre": "Meeting Minutes",
    "publisher": {
        "@type": "Organization",
        "name": "World Wide Web Consortium",
        "url": "https://www.w3.org"
    },
    "recordedAt": {
        "type": "Event",
        "name": "JSON-LD Working Group Telco",
        "startDate": "2019-03-29",
        "endDate": "2019-03-29",
        "attendee": [{
            "type": "Person",
            "name": "Rob Sanderson",
            "description": "chair, scribe"
        }, {
            "type": "Person",
            "name": "Gregg Kellogg"
        }, {
            "type": "Person",
            "name": "Adam Soroka"
        }, {
            "type": "Person",
            "name": "Pierre-Antoine Champin",
            "description": "scribe"
        }]
    }
}
```

Do you have anything better?

I know there this `Role` thing in schema (you have used it for the WG) but, I must admit, I do not really grasp how to use that:-(

**Comment by BigBlueHat** [comment]
Looks like a great start overall, @iherman!

You can think of the Role stuff a bit like "stand-ins" for the Real Thing that fills the role--and then the Real Thing (human, organization, etc) "fills" that role by being a member of it.

So, our meetings potentially include roles with names like `scribe`, `chair`, and `guest`, so the above becomes:
```json
        "attendee": [{
            "type": "OrganizationRole",
            "roleName": "chair",
            "member": {
              "type": "Person",
              "name": "Rob Sanderson"
            }
        }, {
            "type": "Role",
            "roleName": "scribe",
            "member": [{
              "type": "Person",
                "name": "Rob Sanderson"
            }, {
              "type": "Person",
              "name": "Pierre-Antoine Champin"
            }]
        }, {
            "type": "Person",
            "name": "Gregg Kellogg"
        }, {
            "type": "Person",
            "name": "Adam Soroka"
        }]
```

Essentially, `chair` and `scribe` are always present in the `attendee` list, and they get filled later (and can even keep the `startDate`/`endDate` timestamps if we wanted). Everyone else would simply be a direct attendee of the event.

The modeling advantage is that we could collect data around who scribed when without describing Rob personally has a "chair, scribe." 😉

**Comment by iherman** [comment]
@BigBlueHat that of course makes sense, but... the specification of [attendee](https://schema.org/attendee) claims that the value must be a `Person` or an `Organization`. Is it understood that a `Role` can take the place of any other type? Or should we consider that type of requirement as suggestion only?

**Comment by BigBlueHat** [comment]
Yeah...it's not spelled out in their documentation, but it seems that "Role" can replace any `Person` or `Organization` (at least). For example, here's the description of https://schema.org/hasOccupation:
> The Person's occupation. For past professions, use Role for expressing dates.

The Structured Data Testing Tool (fwiw) doesn't seem to care if there's a Role in place of a person. Amusingly, though, it seems to think Event's MUST have locations...which isn't expressed anywhere either.

Perhaps a means to express these sorts of requirements should be explored by a certain JSON-LD WG? 😁

**Comment by iherman** [comment]
@BigBlueHat sigh... yes, I found out the issue around Events, actually, which made my original proposal questionable. As for the role of Role (sic!): well, let us say, no comments...

I will go for your version. At some point, because my day today is full...

**Comment by iherman** [comment]
@BigBlueHat I have made a version with the json-ld preamble; it was fairly easy after all. It is in the `schema-data-to-minutes` branch; the files you may want to look at are:

- https://github.com/w3c/scribejs/blob/schema-data-to-minutes/lib/schema.js : the code implementation that stuff
- Two examples for minutes generated with that preamble:
    - https://github.com/w3c/scribejs/blob/schema-data-to-minutes/test/json-ld-preamble-examples/2019-03-15-json-ld.md
    - https://github.com/w3c/scribejs/blob/schema-data-to-minutes/test/json-ld-preamble-examples/2019-04-01-pwg.md

The fact that the `Event` does not have a location is just a pain, but I am not sure we can do anything about it. In theory, I could add something like:

```
"location" : "Teleconference bridge"
```

but, strangely enough, this is not accepted by the playground either, asking for a full-blown location object, although the definition of `location` allows for `Text`...

Maybe we can just ignore this.

Any comments are welcome!

**Comment by iherman** [comment]
Incorporated into the latest release.
