### ISSUE TITLE
Markdown id format

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/scribejs#59]
@iherman the `[Configuration files](id:conf)` style fragment identifier format doesn't seem to be supported by GitHub Flavored Markdown (which doesn't seem to have this feature at all...sadly) nor by [Kramdown](https://kramdown.gettalong.org/syntax.html#inline-attribute-lists) (which uses the `{: #identifier}` style).

Are you OK if I remove it? It appears in both the output and the README.md.

**Comment by iherman** [comment]
Go ahead!
