### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [w3c/scribejs#76]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/w3c/scribejs/blob/master/package.json#L41

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by iherman** [comment]
I know `fs` is an internal module. The reason I usually do an `npm install` even for these cases is more for documentation purposes, to document what modules the library depends on, whether it is internal or not. It does not do any harm: what `npm` does at installation is just to put a placeholder subdirectory in the `node_modules` directory with a simple README and a `package.json`; no code is actually installed. I.e., the extra costs is essentially none.

Do you see any major reason why this should _not_ be part of `package.json`?

**Comment by DanielRuf** [comment]
Well, there are packages like `path`, `http`, `https` and so on which are also inteenal modules but also available on npmjs but contain a completely different code.

Not sure what you want to document but modules like `fs`, `path`, ... are not needed in package.json.

So it depends on the package what you get. Also the security holding packages often throw a warning during install.

I do not recommend this as this might confuse people who then think that they have to install `fs` and other internal modules which might run unwanted code as part of `install` or `postinstall`.

**Comment by iherman** [comment]
Removed fs
