### ISSUE TITLE
Set up automatic testing

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#8]
A comprehensive test suite would be ideal, of course.

But for now, we can make do with the simplest test: feed scribejs a minimal, fixed IRC log, and check that there's an output and that the output contains certain expected strings.

Test it both as a CLI tool and as a CGI script, if feasible.

That'd allow us to use Travis CI and have it running this test automatically for each new commit or PR, which is useful to quickly identify critical bugs, of the kind that completely break the tool.

**Comment by iherman** [comment]
There is indeed no systematic test suite; I have tested it via existing irc logs and I used it for the various groups I work with the past few days. When some error occurred, I used the real life irc logs to chase down the problem.

Some test irc logs and configuration files are present in the `test` folder. For example, the command

```
scribejs -c test/config.json test/poe-test.txt
```

(Run at the top level, that is) 'rocks' the script in many respect. And there are some other txt files in the same directory that should produce proper results, too. I am not sure how to set up travis, though.

**Comment by tripu** [comment]
Good thing there are sample files already.

I'll explain to you how to automate this, or I will submit a PR myself, @iherman.

**Comment by iherman** [comment]
> On 15 Jun 2017, at 10:36, tripu <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Good thing there are sample files already.
> 
> 

I can add, if needed, several full logs a week:-)



> I'll explain to you how to automate this, or I will submit a PR myself, @iherman <https://github.com/iherman>.
> 
> 

Thanks!
