### ISSUE TITLE
Browserify the tool?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#9]

**Comment by iherman** [comment]
As you said on the call, even if we did that, we have to translate the code to remove the latest Javascript features (alas!). I would be happy to look into this, but I would consider this as a Version2 :-)

**Comment by tripu** [comment]
Also, we'd have to look into cross-origin restrictions and enable CORS for public IRC logs, if this ever runs on a browser.

**Comment by iherman** [comment]
This has been done.
