### ISSUE TITLE
Security alert on marked version

### ISSUE THREAD

**Issue by gkellogg** [w3c/scribejs#93]
We're getting a [security alert](https://github.com/w3c/json-ld-wg/security/dependabot/package-lock.json/marked/open) on w3c/json-ld-wg, and probably others, apparently due to a dependency on "marked" from scribejs. I presume corrective action is required in any repo that has scribejs in its package-lock.json, but it would seemly start with this repo.

Recommendation is to change dependency to `"marked": ">=4.0.10"`, but that may have some implications on the code.

**Comment by iherman** [comment]
Right. But a jump from 2.* to 4.* may be significant, and I am hesitant to blindly upgrade; as you say, there may be implication on the code.

I prefer to do an update locally and do some tests before taking this.

**Comment by iherman** [comment]
But it may take some time... :-(
